# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://42.194.133.29:9090/auth/user/register
Content-Type: application/json

{
    "userName": "jasonZeng",
    "password": "hellojason"
}

###
POST http://42.194.133.29:9090/auth/user/login
Content-Type: application/json

{
    "userName": "jasonZeng",
    "password": "hellojason"
}

###
// 98062d8d-dc33-41c0-a087-d1c702923df7
POST http://42.194.133.29:9090/auth/user/logout
Content-Type: application/json

{
    "userName": "jasonZeng",
    "sessionId": "98062d8d-dc33-41c0-a087-d1c702923df7"
}

### f8b9d904-e774-43c9-8830-d3467c0a9f61
POST http://42.194.133.29:9090/directmessage?sessionId=bc9d52b2-6b4c-4acf-a974-c1c66602b370&userName=jasonZeng&qos=1&tels=183000000
Content-Type: application/json

{
    "title": "test",
    "content": "test-content"
}

###


###
