---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2021-12-25 18:09
---

if redis.call('setnx', KEYS[1], ARGV[1]) == 1 then
    redis.call('pexpire', KEYS[1], ARGV[2])
    return 1
elseif redis.call('get', KEYS[1]) > 0 then
        redis.call('INCR', -1)
        return 1
else
    return 0
end
