server:
  port: 8080
spring:
  redis:
    host: 42.194.133.29
    password: come$%cabbyy!
logging:
  level:
    gateway:
      cmcc:
        com:
          http:
            feign:
              SmsFeign: debug

local:
  request-url: http://localhost:8080